resolver: ghc-8.0.2
# resolver: lts-10.5

packages:
- .

extra-deps: [
  # Lilypond + MIDI
  lilypond-1.9.0
, midi-0.2.2.2
, data-default-0.7.1.1
, event-list-0.1.2
, explicit-exception-0.1.9.2
, monoid-transformer-0.0.4
, music-dynamics-literal-1.9.0
, music-pitch-literal-1.9.0
, non-negative-0.1.2
, prettify-1.0
, process-1.2.3.0
, semigroups-0.18.4
, utility-ht-0.0.14
, vector-space-0.13
, Boolean-0.2.4
, MemoTrie-0.6.9
, NumInstances-1.4
, base-4.8.2.0
, data-default-class-0.1.2.0
, data-default-instances-containers-0.0.1
, data-default-instances-dlist-0.0.1
, data-default-instances-old-locale-0.0.1
, directory-1.2.7.1
, dlist-0.8.0.4
, newtype-generics-0.5.2.1
, old-locale-1.0.0.7
, QuickCheck-2.11.3
, random-1.1
, tf-random-0.5
, primitive-0.6.3.0
  # Euterpea
, Euterpea-2.0.4
, HCodecs-0.5
, PortMidi-0.1.5.2
, arrows-0.4.4.1
, heap-1.0.3
, stm-2.4.5.0
, Stream-0.4.7.2
, lazysmallcheck-0.6
  # Tests
, test-framework-0.8.2.0
, test-framework-hunit-0.3.0.2
, test-framework-quickcheck2-0.3.0.4
, HUnit-1.6.0.0
, ansi-terminal-0.8.0.1
, ansi-wl-pprint-0.6.8.2
, extensible-exceptions-0.1.1.4
, hostname-1.0
, regex-posix-0.95.2
, xml-1.3.14
, call-stack-0.1.0
, colour-2.3.4
, regex-base-0.93.2
, text-1.2.3.0
, mtl-2.2.2
, derive-2.6.3
, haskell-src-exts-1.19.1
, syb-0.7
, uniplate-1.6.12
, cpphs-1.20.8
, hashable-1.2.6.1
, unordered-containers-0.2.9.0
, old-time-1.1.0.3
, polyparse-1.12
  # Vec
, template-haskell-2.11.1.0
]

allow-newer: true
