resolver: ghc-8.0.2
# resolver: lts-10.5

packages:
- .

extra-deps: [
  lilypond-1.9.0
, midi-0.2.2.2
, data-default-0.7.1.1
, event-list-0.1.2
, explicit-exception-0.1.9.2
, monoid-transformer-0.0.4
, music-dynamics-literal-1.9.0
, music-pitch-literal-1.9.0
, non-negative-0.1.2
, prettify-1.0
, process-1.2.3.0
, semigroups-0.18.4
, utility-ht-0.0.14
, vector-space-0.13
, Boolean-0.2.4
, MemoTrie-0.6.9
, NumInstances-1.4
, base-4.8.2.0
, data-default-class-0.1.2.0
, data-default-instances-containers-0.0.1
, data-default-instances-dlist-0.0.1
, data-default-instances-old-locale-0.0.1
, directory-1.2.7.1
, dlist-0.8.0.4
, newtype-generics-0.5.2.1
, old-locale-1.0.0.7
, QuickCheck-2.11.3
, random-1.1
, tf-random-0.5
, primitive-0.6.3.0
, Euterpea-2.0.4
, HCodecs-0.5
, PortMidi-0.1.5.2
, arrows-0.4.4.1
, heap-1.0.3
, stm-2.4.5.0
, Stream-0.4.7.2
, lazysmallcheck-0.6
]

allow-newer: true
